security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        admins:
            memory:
                users:
                    admin@gmail.com: { password: '$2y$13$uhWP/Hc2aTnSHLG2WpIWoOg7P46bV641b/nfzVqVkVbMBItaTV9DO', roles: [ 'ROLE_ADMIN' ] }
        chain_provider:
            chain:
                providers: [admins, app_user_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: chain_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: logout

    access_control:
        - { path: ^/index, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
